name: ruff
on:
    push:
        branches:
            - documents

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.12
            - run: pip install ruff
            - run: |
                  ruff check . --exclude "docs/
                  ruff --fix . --exclude "docs/
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "style fixes by ruff"
